### ISSUE TITLE
Image uploads may fail when this extension is installed

### ISSUE THREAD

**Issue by EddyLB** [ramack/exiftool_gps#3] opened 2018-05-13 12:40 UTC
The API [pwg.images.upload](http://piwigo.org/demo/tools/ws.htm#top) may fail when this extension is installed because it sometimes return a warning in addition to the data returned by the API. For example:

```
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/home/e-smith/files/ibays/album/html/plugins/exiftool_gps/main.inc.php</b> on line <b>23</b><br />
{"stat":"ok","result":{"image_id":30606,"src":"https:\/\/______.com\/_data\/i\/galleries\/Community\/IMG_0003-th.jpg","name":"IMG 0003","category":{"id":341,"nb_photos":"8","label":"Community"}}}
```
while the server should have returned:
```
{"stat":"ok","result":{"image_id":30606,"src":"https:\/\/______.com\/_data\/i\/galleries\/Community\/IMG_0003-th.jpg","name":"IMG 0003","category":{"id":341,"nb_photos":"8","label":"Community"}}}
```
Could this be fixed?

**Comment by ramack** [comment] 2018-05-13 14:37
I guess this is a duplicate of #2 and means, that on your server the exiftool binary is not installed.
Please reopen if this is not the case.

**Closed as completed by ramack** 2018-05-13 14:37 UTC

**Comment by EddyLB** [comment] 2018-05-13 14:42
Thanks. I ask the iOS user to check its installation of exiftool.

**Comment by ramack** [comment] 2018-05-13 14:53
???

exiftool is needed to be installed on the server hosting your piwigo gallery. I guess this is not on iOS...

**Comment by EddyLB** [comment] 2018-05-13 15:03
Yes, of course, the installation of the binary on the server.

The problem is the following: when uploading an image with the iOS app, your extension returns the error in front of the JSON data returned by the Piwigo API. The iOS app cannot interpret this non JSON answer and returns an error preventing the user to upload the image.

It would be preferable to send the warning by email to the admin of the Piwigo server instead of returning an error in HTML which prevents the user from uploading photos. Could you do that?

**Comment by ramack** [comment] 2018-05-13 16:39
this is what is part of #2. But I do not know how to report the warning properly. Would be the best to check the availability in admin section...
